version = 1

[collision_masks]
bottom_half = 0b11
right_half = 0b101
left_half = 0b1010
top_half = 0b1100
full = 0b1111

[[tiles]]
slug = "empty"
sprite_sheet = "background"
simple_key = "."


[[tiles]]
slug = "sand"
sprite_sheet = "background"
sprite = "sand"
collision_mask = "full"

[[tiles]]
slug = "sand_wave"
sprite_sheet = "background"
sprite = "sand_wave"
collision_mask = "full"

[[tiles]]
slug = "sand_lines"
sprite_sheet = "background"
sprite = "sand_lines"
collision_mask = "full"

[[tiles]]
slug = "sand_dune"
sprite_sheet = "background"
sprite = "sand_dune"
collision_mask = "full"

[[tiles]]
slug = "void"
sprite_sheet = "background"
sprite = "void"

[[tiles]]
slug = "arch_left"
sprite_sheet = "background"
sprite = "arch_left"
collision_mask = "left_half"

[[tiles]]
slug = "arch_center"
sprite_sheet = "background"
sprite = "arch_center"

[[tiles]]
slug = "arch_right"
sprite_sheet = "background"
sprite = "arch_right"
collision_mask = "right_half"

[[tiles]]
slug = "battlement"
sprite_sheet = "background"
sprite = "battlement"
collision_mask = "full"

[[tiles]]
slug = "battlement_1"
sprite_sheet = "background"
sprite = "battlement_1"
collision_mask = "full"

[[tiles]]
slug = "bridge_rails"
sprite_sheet = "background"
sprite = "bridge_rails"

[[tiles]]
slug = "cannon_top"
sprite_sheet = "background"
sprite = "cannon_top"
collision_mask = "full"

[[tiles]]
slug = "cannon_center"
sprite_sheet = "background"
sprite = "cannon_center"
collision_mask = "full"

[[tiles]]
slug = "cannon_bottom"
sprite_sheet = "background"
sprite = "cannon_bottom"
collision_mask = "full"

[[tiles]]
slug = "conveyor_corner_left"
sprite_sheet = "background"
sprite = "conveyor_corner_left"

[[tiles]]
slug = "conveyor_horizontal"
sprite_sheet = "background"
sprite = "conveyor_horizontal"

[[tiles]]
slug = "conveyor_right"
sprite_sheet = "background"
sprite = "conveyor_right"

[[tiles]]
slug = "conveyor_vertical"
sprite_sheet = "background"
sprite = "conveyor_vertical"

[[tiles]]
slug = "ladder"
sprite_sheet = "background"
sprite = "ladder"
collision_mask = "full"

[[tiles]]
slug = "beanstalk"
sprite_sheet = "background"
sprite = "beanstalk"
collision_mask = "full"

[[tiles]]
slug = "mound_top"
sprite_sheet = "background"
sprite = "mound_top"

[[tiles]]
slug = "mound_left_45"
sprite_sheet = "background"
sprite = "mound_left_45"

[[tiles]]
slug = "mound_left"
sprite_sheet = "background"
sprite = "mound_left"

[[tiles]]
slug = "mound_center"
sprite_sheet = "background"
sprite = "mound_center"

[[tiles]]
slug = "mound_right"
sprite_sheet = "background"
sprite = "mound_right"

[[tiles]]
slug = "mound_right_45"
sprite_sheet = "background"
sprite = "mound_right_45"

[[tiles]]
slug = "treetop_left"
sprite_sheet = "background"
sprite = "treetop_left"

[[tiles]]
slug = "treetop_center"
sprite_sheet = "background"
sprite = "treetop_center"

[[tiles]]
slug = "treetop_right"
sprite_sheet = "background"
sprite = "treetop_right"

[[tiles]]
slug = "mushroom_left"
sprite_sheet = "background"
sprite = "mushroom_left"
collision_mask = "full"

[[tiles]]
slug = "mushroom_center"
sprite_sheet = "background"
sprite = "mushroom_center"
collision_mask = "full"

[[tiles]]
slug = "mushroom_right"
sprite_sheet = "background"
sprite = "mushroom_right"
collision_mask = "full"

[[tiles]]
slug = "leaves"
sprite_sheet = "background"
sprite = "leaves"

[[tiles]]
slug = "lollipop_top"
sprite_sheet = "background"
sprite = "lollipop_top"

[[tiles]]
slug = "lollipop"
sprite_sheet = "background"
sprite = "lollipop"

[[tiles]]
slug = "lollipop_bottom"
sprite_sheet = "background"
sprite = "lollipop_bottom"

[[tiles]]
slug = "water_top"
sprite_sheet = "background"
sprite = "water_top"

[[tiles]]
slug = "water"
sprite_sheet = "background"
sprite = "water"

[[tiles]]
slug = "piano"
sprite_sheet = "background"
sprite = "piano"
collision_mask = "full"
