version = 1

[collision_masks]
full = 0b1111

[[tiles]]
slug = "item_box"
sprite_sheet = "item_box"
sprites = [
    { sprite = "item_box_1", frames = 24 },
    { sprite = "item_box_2", frames = 8 },
    { sprite = "item_box_3", frames = 8 },
    { sprite = "item_box_2", frames = 8 },
]
collision_mask = "full"
simple_key = "?"

[[tiles]]
slug = "coin"
sprite_sheet = "items"
sprites = [
    { sprite = "coin_1", frames = 24 },
    { sprite = "coin_2", frames = 8 },
    { sprite = "coin_3", frames = 8 },
    { sprite = "coin_2", frames = 8 },
]
category = "collectable"
simple_key = "$"

[[tiles]]
slug = "item_box_used"
sprite_sheet = "item_box"
sprite = "item_box_used"
collision_mask = "full"
