version = 1

[collision_masks]
full = 0b1111

[[tiles]]
slug = "item_box"
sprite_sheet = "coins"
sprites = [
    { sprite = "item_box_1", frames = 24 },
    { sprite = "item_box_2", frames = 8 },
    { sprite = "item_box_3", frames = 8 },
    { sprite = "item_box_2", frames = 8 },
]
collision_mask = "full"
simple_key = "?"

[[tiles]]
slug = "item_box_used"
sprite_sheet = "coins"
sprite = "item_box_used"
collision_mask = "full"
