version = 1

[[tiles]]
slug = "flagpole_top"
sprite_sheet = "pipes_and_scenery"
sprite = "flagpole_top"

[[tiles]]
slug = "flagpole"
sprite_sheet = "pipes_and_scenery"
sprite = "flagpole"

[[tiles]]
slug = "flag"
sprite_sheet = "objects"
sprite = "flag"
