"""Gameplay configuration and shared HUD helpers."""

from .config import (
    HUD_COIN_DIGITS,
    HUD_COIN_INCREMENT,
    HUD_COIN_SCORE_VALUE,
    HUD_DEFAULT_TIMER_START,
    HUD_SCORE_DIGITS,
    HUD_TIMER_DIGITS,
    HUD_TIMER_FRAMES_PER_DECREMENT,
    SCORE_POPUP_LIFETIME_FRAMES,
    SCORE_POPUP_UPWARD_SPEED,
    SCORE_POPUP_VERTICAL_OFFSET,
)

__all__ = [
    "HUD_COIN_DIGITS",
    "HUD_COIN_INCREMENT",
    "HUD_COIN_SCORE_VALUE",
    "HUD_DEFAULT_TIMER_START",
    "HUD_SCORE_DIGITS",
    "HUD_TIMER_DIGITS",
    "HUD_TIMER_FRAMES_PER_DECREMENT",
    "SCORE_POPUP_LIFETIME_FRAMES",
    "SCORE_POPUP_UPWARD_SPEED",
    "SCORE_POPUP_VERTICAL_OFFSET",
]
